<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD -->

<!DOCTYPE biblioteca [

    <!-- Elementos -->

    <!-- global -->
    <!ELEMENT biblioteca ( libro*, revista*, periodico* )>

    <!-- Libro -->
    <!ELEMENT libro ( titulo_libro+, capitulo_libro+, indice_libro+, sinopsis_libro+ )>
    <!ELEMENT capitulo_libro ( titulo_capitulo+, contenido_capitulo+ )>
    <!ELEMENT titulo_libro ( #PCDATA )>
    <!ELEMENT indice_libro ( #PCDATA )>
    <!ELEMENT sinopsis_libro ( #PCDATA )>
    <!ELEMENT titulo_capitulo ( #PCDATA )>
    <!ELEMENT contenido_capitulo ( #PCDATA )>

    <!-- Revista -->
    <!ELEMENT revista ( titulo_revista+, numero_revista+, indice_revista+, seccion_revista+ )>
    <!ELEMENT seccion_revista ( contenido_revista+ )>
    <!ELEMENT titulo_revista ( #PCDATA )>
    <!ELEMENT numero_revista ( #PCDATA )>
    <!ELEMENT indice_revista ( #PCDATA )>
    <!ELEMENT contenido_revista ( #PCDATA )>

    <!-- Periodico -->
    <!ELEMENT periodico ( seccion_periodico+, indice_periodico+ )>
    <!ELEMENT seccion_periodico ( articulo_periodico+ )>
    <!ELEMENT articulo_periodico ( contenido_articulo+ )>
    <!ELEMENT indice_periodico ( #PCDATA )>
    <!ELEMENT contenido_articulo ( #PCDATA )>

    <!-- Atributos -->

    <!-- Libro -->
    <!ATTLIST libro
        id ID #REQUIRED
        tipo_clase ( novela | infantil | didactico ) #REQUIRED
        numero_paginas_libro CDATA #REQUIRED
    >
    <!ATTLIST capitulo_libro numero_paginas_capitulo CDATA #REQUIRED>
    <!ATTLIST contenido_capitulo enlace_capitulo CDATA #REQUIRED>

    <!-- Revista -->
    <!ATTLIST revista
        id ID #REQUIRED
        tipo_clase ( informatica | corazon | coches | investigacion | otras ) #REQUIRED
        numero_paginas_revista CDATA #REQUIRED
    >
    <!ATTLIST seccion_revista numero_paginas_seccion CDATA #REQUIRED>
    <!ATTLIST contenido_revista enlace_cont CDATA #REQUIRED>

    <!-- Periodico -->
    <!ATTLIST periodico
        id ID #REQUIRED
        tipo_clase ( nacional | internacional ) #REQUIRED
        fecha_publicacion CDATA #REQUIRED
    >
    <!ATTLIST seccion_periodico tipo_seccion ( economica | opinion | deportes | nacional | internacional ) #REQUIRED>
    <!ATTLIST articulo_periodico autor CDATA #REQUIRED>
    <!ATTLIST contenido_articulo enlace_periodico CDATA #REQUIRED>

]>

<!-- XML -->

<biblioteca>

    <!-- Libro -->

    <libro id="L1001" tipo_clase="novela" numero_paginas_libro="215">
        <titulo_libro>
            Título del Libro.
        </titulo_libro>
        <capitulo_libro numero_paginas_capitulo="25">
            <titulo_capitulo>
                Nombre del primer capitulo.
            </titulo_capitulo>
            <contenido_capitulo enlace_capitulo="enlace" />
        </capitulo_libro>
        <indice_libro>
            El indice del libro.
        </indice_libro>
        <sinopsis_libro>
            La sinopsis del libro.
        </sinopsis_libro>
    </libro>

    <!-- Revista -->

    <revista id="R2001" tipo_clase="informatica" numero_paginas_revista="33">
        <titulo_revista>
            Título de la Revista.
        </titulo_revista>
        <numero_revista>
            002.
        </numero_revista>
        <indice_revista>
            El indice de la Revista.
        </indice_revista>
        <seccion_revista numero_paginas_seccion="7">
            <contenido_revista enlace_cont="enlace"/>
        </seccion_revista>
    </revista>

    <!-- Periodico -->

    <periodico id="P3001" tipo_clase="nacional" fecha_publicacion="13/05/2022">
        <seccion_periodico tipo_seccion="economica">
            <articulo_periodico autor="nombre">
                <contenido_articulo enlace_periodico="enlace"/>
            </articulo_periodico>
        </seccion_periodico>
        <indice_periodico>
            El índice del periodico.
        </indice_periodico>
    </periodico>

</biblioteca>