=== PABLOKUMAR1993/AE2-Lenguajes/Proyecto_final/xsd_biblioteca.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="biblioteca">
        <complexType>
            <sequence>
<!-- AÑADIMOS LOS LIBROS-->
                <element name="libros">
                    <complexType>
                        <sequence>
                            <element name="libro">
                                <complexType>
                                    <sequence>
                                        <element name="titulo_libro" type="string"/>
                                        <element name="indice_libro" type="string"/>
                                        <element name="sinopsis_libro" type="string"/>
                                        <element name="capitulos_libros">
                                            <complexType>
                                                <sequence>
                                                    <element name="capitulo_libro" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="titulo_capitulo" type="string"/>
                                                                <element name="contenido_capitulo">
                                                                    <complexType>
                                                                        <sequence></sequence>
                                                                        <attribute name="enlace_capitulo" type="string"/>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="numero_paginas_capitulo" type="string"/>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="id" type="string"/>
                                    <attribute name="tipo_clase" type="string"/>
                                    <attribute name="numero_paginas_libro" type="short"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
<!-- AÑADIMOS LAS REVISTAS-->
                <element name="revistas">
                    <complexType>
                        <sequence>
                            <element name="revista">
                                <complexType>
                                    <sequence>
                                        <element name="titulo_revista" type="string"/>
                                        <element name="numero_revista" type="short"/>
                                        <element name="indice_revista" type="string"/>
                                        <element name="secciones_revista">
                                            <complexType>
                                                <sequence>
                                                    <element name="seccion_revista" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="titulo_seccion" type="string"/>
                                                                <element name="contenido_seccion_enlace">
                                                                    <complexType>
                                                                        <sequence></sequence>
                                                                        <attribute name="enlace_revista" type="string"/>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="numero_paginas_seccion" type="short"/>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="id" type="string"/>
                                    <attribute name="tipo_clase" type="string"/>
                                    <attribute name="numero_paginas_revista" type="short"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
<!-- AÑADIMOS LOS PERIDICOS-->
                <element name="periodicos">
                    <complexType>
                        <sequence>
                            <element name="periodico">
                                <complexType>
                                    <sequence>
                                        <element name="titulo_periodico" type="string"/>
                                        <element name="indice_periodico" type="string"/>
                                        <element name="secciones_periodico">
                                            <complexType>
                                                <sequence>
                                                    <element name="seccion_periodico" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="articulos_seccion">
                                                                    <complexType>
                                                                        <sequence>
                                                                            <element name="articulo_seccion" maxOccurs="unbounded">
                                                                                <complexType>
                                                                                    <sequence>
                                                                                        <element name="contenido_articulo_enlace">
                                                                                            <complexType>
                                                                                                <sequence></sequence>
                                                                                                <attribute name="enlace_periodico" type="string"/>
                                                                                            </complexType>
                                                                                        </element>
                                                                                    </sequence>
                                                                                    <attribute name="autor" type="string"/>
                                                                                </complexType>
                                                                            </element>
                                                                        </sequence>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="tipo_seccion" type="string"/>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="id" type="string"/>
                                    <attribute name="tipo_clase" type="string"/>
                                    <attribute name="fecha_publicacion" type="date"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== PABLOKUMAR1993/AE2-Lenguajes/Proyecto_final/biblioteca_con_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Enunciado
Vamos a elaborar una estructura de base de datos en XML que permita almacenar los datos de una biblioteca en la red con las siguientes características:
•	Existen tres tipos de documentos almacenados en la biblioteca: libros, revistas y periódicos. Todos los documentos están identificados por el atributo Id.

        o	Para los libros este atributo empieza con la letra “L” seguido de 4 dígitos identificativos.
        o	Para los periódicos este atributo empieza por la letra “P” seguido de los 4 dígitos identificativos.
        o	En el caso de las revistas empieza por la letra “R”.

•	Los libros a su vez son clasificados en novela, infantil o didáctico. Cada libro contiene un atributo identificativo de su clase denominado tipo_clase. Dentro de cada 
    libro se tiene un título, varios capítulos con el título en su interior, un índice y una sinopsis. Tanto en libro como en capítulo existe un atributo que contiene el 
    número de páginas del libro o del capítulo, según corresponda. Cada capítulo contiene un elemento denominado contenido, en el que se tiene un atributo con el enlace a 
    la información.

•	Las revistas a su vez son clasificadas en: informática, corazón, coches, investigación y otras. Cada revista tiene el atributo tipo_clase identificativo de la clase 
    a la que pertenece. Dentro de cada revista tenemos el título, el número de la revista, un índice de contenido y las secciones. En cada sección y en la revista se tiene 
    un atributo que contiene el número de páginas. Además, en cada sección se tiene la parte denominada contenido, en la que se tiene un atributo con un enlace a la información.

•	Los periódicos se clasifican en nacionales e internacionales. Cada periódico contiene el atributo tipo_clase identificativo de la clase a la que pertenece y un atributo
    que incluye la fecha de publicación. Dentro de los periódicos tenemos secciones y un índice. Cada sección debe contener un atributo identificativo del tipo de sección, 
    que puede ser: económica, opinión, deportes, nacional o internacional. Las secciones se dividen en artículos, en donde se define en un atributo el autor. 
    Finalmente, el contenido será el último elemento del árbol, que necesita un atributo que referencie a la información.

Requerimiento 1
    Crear un XML con el modelo de datos indicado en el enunciado.
    Elaborar un DTD que permita validar el documento XML.
    Validar el documento con alguna aplicación externa e incluir capturas de pantalla.
    IMPORTANTE: Cada alumno propondrá una solución de XML y DTD. Una vez todos los alumnos hayan puesto todas sus soluciones, se cotejará con el resto para poner la solución final.
    Valoración: 5 puntos sobre 10

Requerimiento 2
    Elaborar un XSD que permita validar el documento XML.
    Validar el documento con alguna aplicación externa e incluir capturas de pantalla.
    IMPORTANTE: Cada alumno propondrá una solución de XML y XSD. Una vez todos los alumnos hayan puesto todas sus soluciones, se cotejará con el resto para poner la solución final.
 -->
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "xsd_biblioteca.xsd">

<!-- AÑADIMOS LOS LIBROS-->

    <libros>
        <libro id="L0001"  tipo_clase ="novela" numero_paginas_libro ="456">
            <titulo_libro>20.000 leguas de viaje submarino</titulo_libro>
            <indice_libro> Este es el indice del libro </indice_libro>
            <sinopsis_libro> Esta es la sinopsis del libro </sinopsis_libro>
            <capitulos_libros>
                <capitulo_libro numero_paginas_capitulo="27">
                    <titulo_capitulo>20.000 leguas de viaje submarino</titulo_capitulo>
                    <contenido_capitulo enlace_capitulo="www.enlace.com"/>
                </capitulo_libro>
                <capitulo_libro numero_paginas_capitulo="43">
                    <titulo_capitulo>El monstruo metálico</titulo_capitulo>
                    <contenido_capitulo enlace_capitulo="www.enlace.com"/>
                </capitulo_libro>
            </capitulos_libros>
        </libro>
    </libros>  

<!-- AÑADIMOS LAS REVISTAS-->

    <revistas>
        <revista id="R0001" tipo_clase ="investigacion" numero_paginas_revista="75">
            <titulo_revista>Geo</titulo_revista>
            <numero_revista>1</numero_revista>
            <indice_revista>Este es el índice de la revista</indice_revista>
            <secciones_revista>
                <seccion_revista numero_paginas_seccion ="5">
                    <titulo_seccion>Metamorfosis</titulo_seccion>
                    <contenido_seccion_enlace enlace_revista="https://www.enlace.com"/>
                </seccion_revista>
            </secciones_revista>
        </revista>
    </revistas>

<!-- AÑADIMOS LOS PERIÓDICOS -->

    <periodicos>
        <periodico id="P0001" tipo_clase="nacional" fecha_publicacion="03/05/2022">
            <titulo_periodico>El Pais</titulo_periodico>
            <indice_periodico> Este es el índice del periodico </indice_periodico> 
            <secciones_periodico>
                <seccion_periodico tipo_seccion="economica">
                    <articulos_seccion>
                        <articulo_seccion autor="Jose Carlos Díez">
                            <contenido_articulo_enlace enlace_periodico="https://www.enlace.com"/>
                        </articulo_seccion>
                        <articulo_seccion autor="Elisenda Paluzie">
                            <contenido_articulo_enlace enlace_periodico="https://www.enlace.com"/>
                        </articulo_seccion>
                    </articulos_seccion>
                </seccion_periodico>
                <seccion_periodico tipo_seccion="nacional">
                    <articulos_seccion>
                        <articulo_seccion autor="Gabriela Cañas">
                            <contenido_articulo_enlace enlace_periodico="https://www.enlace.com"/>
                        </articulo_seccion>
                        <articulo_seccion autor="Jesus Mota">
                            <contenido_articulo_enlace enlace_periodico="https://www.enlace.com"/>
                        </articulo_seccion>
                    </articulos_seccion>
                </seccion_periodico>
            </secciones_periodico>
        </periodico>
    </periodicos>
</biblioteca>
