=== PABLOKUMAR1993/AE2-Lenguajes/PAVLO/XSD/biblioteca.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">

    <!--NOTAS-->

    <annotation>
        <documentation>
            Esquema mediante XSD para la actividad AE2 de Lenguajes.
        </documentation>
    </annotation>

    <!--GENERAL-->

    <element name="biblioteca">
        <complexType>
            <sequence> <!--Puedo necesitar enviar un libro, varios o ninguno, porque por ejemplo sólo puedo tener revistas en un momento dado-->

                <!--LIBRO-->

                <element name="libros">
                    <complexType>
                        <sequence>
                            <element name="libro">
                                <complexType>

                                    <sequence>
                                        <!--Dado que si voy a pasar un libro, entiendo que es obligatoria toda la información y en ese orden concreto-->
                                        <element name="titulo_libro" type="string" />
                                        <element name="capitulo_libro">
                                            <complexType>
                                                <sequence>
                                                    <element name="titulo_capitulo" type="string" />
                                                    <element name="contenido_capitulo">
                                                        <complexType>
                                                            <simpleContent>
                                                                <extension base="string">
                                                                    <attribute name="enlace_capitulo" type="string" use="required" />
                                                                </extension>
                                                            </simpleContent>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                                <attribute name="numero_paginas_capitulo" type="integer" use="required" />
                                            </complexType>
                                        </element>
                                        <element name="indice_libro" />
                                        <element name="sinopsis_libro" />
                                    </sequence>


                                    <attribute name="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <length value="5" />
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="tipo_clase" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="novela" />
                                                <enumeration value="infantil" />
                                                <enumeration value="didactico" />
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="numero_paginas_libro" type="integer" use="required" />

                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>

                <!--REVISTA-->

                <element name="revistas">
                    <complexType>
                        <sequence>
                            <element name="revista">
                                <complexType>

                                    <sequence>
                                        <element name="titulo_revista" type="string" />
                                        <element name="numero_revista" type="integer" />
                                        <element name="indice_revista" type="string" />
                                        <element name="seccion_revista">
                                            <complexType>
                                                <sequence>
                                                    <element name="contenido_revista">
                                                        <complexType>
                                                            <simpleContent>
                                                                <extension base="string">
                                                                    <attribute name="enlace_cont" type="string" use="required" />
                                                                </extension>
                                                            </simpleContent>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                                <attribute name="numero_paginas_seccion" type="integer" use="required" />
                                            </complexType>
                                        </element>
                                    </sequence>


                                    <attribute name="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <length value="5" />
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="tipo_clase" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="informatica" />
                                                <enumeration value="corazon" />
                                                <enumeration value="investigacion" />
                                                <enumeration value="otras" />
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="numero_paginas_revista" type="integer" use="required" />

                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>

                <!--PERIODICO-->

                <element name="periodicos">
                    <complexType>
                        <sequence>
                            <element name="periodico">
                                <complexType>

                                    <sequence>
                                        <element name="seccion_periodico">
                                            <complexType>
                                                <sequence>
                                                    <element name="articulo_periodico">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="contenido_articulo">
                                                                    <complexType>
                                                                        <simpleContent>
                                                                            <extension base="string">
                                                                                <attribute name="enlace_periodico" type="string" use="required" />
                                                                            </extension>
                                                                        </simpleContent>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="autor" type="string" use="required" />
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                                <attribute name="tipo_seccion" use="required">
                                                    <simpleType>
                                                        <restriction base="string">
                                                            <enumeration value="economica" />
                                                            <enumeration value="opinion" />
                                                            <enumeration value="deportes" />
                                                            <enumeration value="nacional" />
                                                            <enumeration value="internacional" />
                                                        </restriction>
                                                    </simpleType>
                                                </attribute>
                                            </complexType>
                                        </element>
                                        <element name="indice_periodico" />
                                    </sequence>


                                    <attribute name="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <length value="5"></length>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="tipo_clase" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="nacional" />
                                                <enumeration value="internacional" />
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="fecha_publicacion" type="date" use="required" />

                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>

            </sequence>
        </complexType>
    </element>

</schema>

=== PABLOKUMAR1993/AE2-Lenguajes/PAVLO/XSD/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- XML -->

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">

    <!-- Libro -->

    <libros>
        <libro id="L1001" tipo_clase="novela" numero_paginas_libro="215">
            <titulo_libro>
                Título del Libro.
            </titulo_libro>
            <capitulo_libro numero_paginas_capitulo="25">
                <titulo_capitulo>
                Nombre del primer capitulo.
            </titulo_capitulo>
                <contenido_capitulo enlace_capitulo="enlace" />
            </capitulo_libro>
            <indice_libro>
            El indice del libro.
            </indice_libro>
            <sinopsis_libro>
            La sinopsis del libro.
        </sinopsis_libro>
        </libro>
    </libros>

    <!-- Revista -->

    <revistas>
        <revista id="R2001" tipo_clase="informatica" numero_paginas_revista="33">
            <titulo_revista>
            Título de la Revista.
        </titulo_revista>
            <numero_revista>
            002
        </numero_revista>
            <indice_revista>
            El indice de la Revista.
        </indice_revista>
            <seccion_revista numero_paginas_seccion="7">
                <contenido_revista enlace_cont="enlace" />
            </seccion_revista>
        </revista>
    </revistas>

    <!-- Periodico -->

    <periodicos>
        <periodico id="P3001" tipo_clase="nacional" fecha_publicacion="2022-05-25">
            <seccion_periodico tipo_seccion="economica">
                <articulo_periodico autor="nombre">
                    <contenido_articulo enlace_periodico="enlace" />
                </articulo_periodico>
            </seccion_periodico>
            <indice_periodico>
            El índice del periodico.
        </indice_periodico>
        </periodico>
    </periodicos>

</biblioteca>
